spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: delivery
    password: password1234@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090